# Generated by Django 4.2.7 on 2023-11-27 10:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kantin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('lokasi', models.TextField()),
                ('deskripsi', models.TextField()),
                ('list_foto', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('status_verifikasi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('list_foto', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('kantin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan_list', to='kantin.kantin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kantin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='kantin.kantin')),
            ],
        ),
    ]
