# Generated by Django 4.2.1 on 2023-11-27 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kantin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kantin',
            name='list_foto',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='kantin',
            name='lokasi',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='kantin',
            name='nama',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='kantin',
            name='status_verifikasi',
            field=models.CharField(choices=[('Terverifikasi', 'Verified'), ('Pending', 'Pending'), ('Tidak terverifikasi', 'Disproved')], default='Pending', max_length=1024),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nama',
            field=models.CharField(max_length=1024),
        ),
    ]
