# Generated by Django 4.2.1 on 2023-12-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kantin', '0002_alter_kantin_list_foto_alter_kantin_lokasi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ulasan',
            old_name='list_foto',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='ulasan',
            old_name='time_created',
            new_name='time',
        ),
    ]
