# Generated by Django 4.2.1 on 2023-11-27 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=1024)),
                ('nomor_telepon', models.CharField(max_length=14)),
                ('is_admin', models.BooleanField(default=False)),
                ('foto', models.URLField()),
                ('role', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Pemilik Kantin', 'Canteen Owner')], default='User', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
