# Generated by Django 4.2.1 on 2023-11-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kantin', '0001_initial'),
        ('authentication', '0002_alter_userinformation_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemilikKantin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kantin', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='kantin', to='kantin.kantin')),
                ('user_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_information', to='authentication.userinformation')),
            ],
        ),
    ]
