# Generated by Django 4.2.1 on 2023-11-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kantin', '0002_alter_kantin_list_foto_alter_kantin_lokasi_and_more'),
        ('authentication', '0003_pemilikkantin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemilikkantin',
            name='kantin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kantin', to='kantin.kantin'),
        ),
    ]
