# Generated by Django 4.2.1 on 2023-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kantin', '0002_alter_kantin_list_foto_alter_kantin_lokasi_and_more'),
        ('authentication', '0005_alter_pemilikkantin_user_information_pengguna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengguna',
            name='kantin_favorit',
        ),
        migrations.AddField(
            model_name='pengguna',
            name='kantin_favorit',
            field=models.ManyToManyField(blank=True, to='kantin.kantin'),
        ),
    ]
