# Generated by Django 4.2.1 on 2023-12-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_pemilikkantin_user_information'),
        ('authentication', '0006_remove_pengguna_kantin_favorit_and_more'),
    ]

    operations = [
    ]
